import Header from "@/components/header/Header";
import { ThemeProvider } from "@/components/theme/theme-trovider/ThemeProvider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon.ico" />
            </head>

            <body className={roboto.className}>
                <ThemeProvider attribute="class" defaultTheme="light">
                    {/* <HeaderOne /> */}
                    <Header />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
